
rating_mapping = {
    "Strong Buy": "Buy",
    "Top Pick": "Buy",
    "Buy": "Buy",
    "Overweight": "Buy",
    "Outperform": "Buy",
    "Above": "Buy",
    "Market Outperform": "Buy",
    "Positive": "Buy",
    "Long-Term Buy": "Buy",
    "Conviction Buy": "Buy",
    "Speculative Buy": "Buy",
    "Neutral": "Hold",
    'Peer Perform': "Hold",
    "Market Perform": "Hold",
    "Perform": "Hold",
    'Sector Weight': "Hold",
    'Sector Perform': "Hold",
    "Average": "Hold",
    "Hold": "Hold",
    "Mixed": "Hold",
    "In-Line": "Hold",
    "In-line": "Hold",
    "Equal-Weight": "Hold",
    "Accumulate": "Hold",
    "Equal Weight": "Hold",
    "Underperform": "Sell",
    "Underweight": "Sell",
    "Negative": "Sell",
    "Underperformer": "Sell",
    "Below Average": "Sell",
    "Sector Underperform": "Sell",
    "Trim": "Sell",
    "Sell": "Sell",
    "Reduce": "Sell",
    "Strong Sell": "Sell"
}